//
//  SChannelListWorker.swift
//  Channel7Test
//
//  Created by Noble Mathew on 30/6/17.
//  Copyright (c) 2017 NTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class SChannelListWorker {
  // MARK: - Business Logic
  
  func fetchData(completion: @escaping([Channel]?) -> ()) {
    
    var finalArray = [Channel]()
    NetworkLayerClass.fetchDataFrom(mainChannelURL) { (data) in
      if let data = data {
        let channelList = data[channelString] as? [[String: Any]]
        if let channelList = channelList {
          
          for channel in channelList {
            let channelID = channel[channelIDString] as? Int
            let channelName = channel[channelNameString] as? String
            let channelDisplayOrder = channel[displayOrderString] as? Int
            
            let channell = Channel(channedID: channelID, channelName: channelName, displayOrder: channelDisplayOrder)
            
            finalArray.append(channell)
          }
          
          completion(finalArray)
        }
        completion(nil)
      }
      completion(nil)
    }
  }
}
