//
//  SChannelListRouter.swift
//  Channel7Test
//
//  Created by Noble Mathew on 30/6/17.
//  Copyright (c) 2017 NTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SChannelListRouterInput {
}

class SChannelListRouter: SChannelListRouterInput {
  weak var viewController: SChannelListViewController!
  
  // MARK: - Navigation
  func passDataToNextScene(segue: UIStoryboardSegue) {
    if segue.identifier == "channelListSegue" {
      let selectedRowIndex = viewController.collectionView.indexPathsForSelectedItems?.first
      if selectedRowIndex != nil {
        let deatilsVC: SChannelDetailsViewController = segue.destination as! SChannelDetailsViewController
        deatilsVC.channelDetails = viewController.channelArray[selectedRowIndex!.item]
      }
    }
  }
}
