//
//  SChannelListConfigurator.swift
//  Channel7Test
//
//  Created by Noble Mathew on 30/6/17.
//  Copyright (c) 2017 NTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension SChannelListViewController: SChannelListPresenterOutput {
  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    router.passDataToNextScene(segue: segue)
  }
}

extension SChannelListInteractor: SChannelListViewControllerOutput {
}

extension SChannelListPresenter: SChannelListInteractorOutput {
}

class SChannelListConfigurator {
  // MARK: - Object lifecycle
  
  static let sharedInstance = SChannelListConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: SChannelListViewController) {
    let router = SChannelListRouter()
    router.viewController = viewController
    
    let presenter = SChannelListPresenter()
    presenter.output = viewController
    
    let interactor = SChannelListInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
