//
//  SChannelListInteractor.swift
//  Channel7Test
//
//  Created by Noble Mathew on 30/6/17.
//  Copyright (c) 2017 NTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SChannelListInteractorInput {
  func fetchChannelData()
}

protocol SChannelListInteractorOutput {
  func relaodData(_ channels: [Channel])
}

class SChannelListInteractor: SChannelListInteractorInput {
  var output: SChannelListInteractorOutput!
  var worker: SChannelListWorker!
  
  // MARK: - Business logic
  func fetchChannelData() {
    worker = SChannelListWorker()
    worker.fetchData { (channels) in
      if let channels = channels {
        self.output.relaodData(channels)
      }
    }
  }
  
}
