//
//  SChannelDetailsConfigurator.swift
//  Channel7Test
//
//  Created by Noble Mathew on 30/6/17.
//  Copyright (c) 2017 NTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension SChannelDetailsViewController: SChannelDetailsPresenterOutput {
}

extension SChannelDetailsInteractor: SChannelDetailsViewControllerOutput {
}

extension SChannelDetailsPresenter: SChannelDetailsInteractorOutput {
}

class SChannelDetailsConfigurator {
  // MARK: - Object lifecycle
  
  static let sharedInstance = SChannelDetailsConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: SChannelDetailsViewController) {
    let router = SChannelDetailsRouter()
    router.viewController = viewController
    
    let presenter = SChannelDetailsPresenter()
    presenter.output = viewController
    
    let interactor = SChannelDetailsInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
