//
//  SChannelDetailsPresenter.swift
//  Channel7Test
//
//  Created by Noble Mathew on 30/6/17.
//  Copyright (c) 2017 NTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SChannelDetailsPresenterInput {
  func updateData(_ channelDetails: [ChannelDetails])
}

protocol SChannelDetailsPresenterOutput: class {
  func updateCollectionView(_ channelDetails: [ChannelDetails])
}

class SChannelDetailsPresenter: SChannelDetailsPresenterInput {
  weak var output: SChannelDetailsPresenterOutput!
  
  // MARK: - Presentation logic
  func updateData(_ channelDetails: [ChannelDetails]) {
    output.updateCollectionView(channelDetails)
  }
}
