//
//  SChannelDetailsRouter.swift
//  Channel7Test
//
//  Created by Noble Mathew on 30/6/17.
//  Copyright (c) 2017 NTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SChannelDetailsRouterInput {
}

class SChannelDetailsRouter: SChannelDetailsRouterInput {
  weak var viewController: SChannelDetailsViewController!
  
  // MARK: - Navigation
  
}
