//
//  SChannelDetailsWorker.swift
//  Channel7Test
//
//  Created by Noble Mathew on 30/6/17.
//  Copyright (c) 2017 NTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class SChannelDetailsWorker {
  // MARK: - Business Logic
  
  func fetchData(_ channelID: Int,completion: @escaping([ChannelDetails]?) -> ()) {
    var finalArray = [ChannelDetails]()
    let url = String(format: channelDetailsURL, channelID)
    NetworkLayerClass.fetchDataFrom(url) { (data) in
      if let data = data {
        let programList = data[programString] as? [[String: Any]]
        if let programList = programList {
          
          for program in programList {
            let programID = program[programIDString] as? Int
            let programTitle = program[programTitleString] as? String
            let programSynopsis = program[programSynopsisString] as? String
            let programStartTime = program[programStartTimeString] as? String
            let programEndTime = program[programEndTimeString] as? String
            let programImageURL = program[programImageURLString] as? String
            
            let programme = ChannelDetails(programID: programID, programTitle: programTitle, programSynopsis: programSynopsis, programStartTime: programStartTime, programEndTime: programEndTime, programImageURL: programImageURL)
            
            finalArray.append(programme)
          }
          
          completion(finalArray)
        }
        completion(nil)
      }
      completion(nil)
    }
  }
}
