//
//  SChannelDetailsInteractor.swift
//  Channel7Test
//
//  Created by Noble Mathew on 30/6/17.
//  Copyright (c) 2017 NTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SChannelDetailsInteractorInput {
  func fetchData(_ channelID: Int)
}

protocol SChannelDetailsInteractorOutput {
  func updateData(_ channelDetails: [ChannelDetails])
}

class SChannelDetailsInteractor: SChannelDetailsInteractorInput {
  var output: SChannelDetailsInteractorOutput!
  var worker: SChannelDetailsWorker!
  
  // MARK: - Business logic
  func fetchData(_ channelID: Int) {
    worker = SChannelDetailsWorker()
    worker.fetchData(channelID) { (channelDetails) in
      if let channelDetails = channelDetails {
        self.output.updateData(channelDetails)
      }
    }
  }
}
